[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 9600
monitor_port = dev/tty.usbmodem197121101

lib_deps =
    adafruit/Adafruit LIS2MDL@^2.1.8
    adafruit/Adafruit GPS Library@^1.7.5